version: 2

formats: [] #all #- epub #- pdf #- htmlzip

sphinx:
  configuration: docs/source/conf.py

build:
  image: latest

python:
  version: 3.7
  pip_install: true
  extra_requirements:
    - docs
